-- SQL THAM KHẢO từ mô hình ERD (kiểu dữ liệu do người viết giả định)
CREATE DATABASE IF NOT EXISTS QuanLyVatTu;
USE QuanLyVatTu;

CREATE TABLE PHIEUXUAT (
 SoPX VARCHAR(20) PRIMARY KEY,
 NgayXuat DATE
);
CREATE TABLE VATTU (
 MaVTU VARCHAR(20) PRIMARY KEY,
 TenVTU VARCHAR(100)
);
CREATE TABLE PHIEUNHAP (
 SoPN VARCHAR(20) PRIMARY KEY,
 NgayNhap DATE
);
CREATE TABLE NHACC (
 MaNCC VARCHAR(20) PRIMARY KEY,
 TenNCC VARCHAR(100),
 DiaChi VARCHAR(255)
);
CREATE TABLE DONDH (
 SoDH VARCHAR(20) PRIMARY KEY,
 NgayDH DATE,
 MaNCC VARCHAR(20),
 CONSTRAINT fk_dondh_nhacc FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);
CREATE TABLE CHITIET_PHIEUXUAT (
 SoPX VARCHAR(20) NOT NULL,
 MaVTU VARCHAR(20) NOT NULL,
 DGXuat DECIMAL(15,2),
 SLXuat INT,
 PRIMARY KEY (SoPX, MaVTU),
 FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
 FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
CREATE TABLE CHITIET_PHIEUNHAP (
 SoPN VARCHAR(20) NOT NULL,
 MaVTU VARCHAR(20) NOT NULL,
 DGNhap DECIMAL(15,2),
 SLNhap INT,
 PRIMARY KEY (SoPN, MaVTU),
 FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
 FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
CREATE TABLE CHITIET_DONDH (
 SoDH VARCHAR(20) NOT NULL,
 MaVTU VARCHAR(20) NOT NULL,
 PRIMARY KEY (SoDH, MaVTU),
 FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
 FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);
CREATE TABLE NHACC_SDT (
 MaNCC VARCHAR(20) NOT NULL,
 SDT VARCHAR(20) NOT NULL,
 PRIMARY KEY (MaNCC, SDT),
 FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);
