-- BAI THUC HANH: TAO BANG TRONG CSDL QUAN LY DIEM THI
-- Chay tren MySQL Workbench / MySQL 8.x
-- Giữ nguyên CSDL nếu đã tồn tại; không xóa bảng hoặc dữ liệu cũ.

CREATE DATABASE IF NOT EXISTS QuanLyDiemThi
  CHARACTER SET utf8mb4;
USE QuanLyDiemThi;

CREATE TABLE IF NOT EXISTS HocSinh (
    MaHS VARCHAR(20) PRIMARY KEY,
    TenHS VARCHAR(50),
    NgaySinh DATETIME,
    Lop VARCHAR(20),
    GT VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS GiaoVien (
    MaGV VARCHAR(20) PRIMARY KEY,
    TenGV VARCHAR(50),
    SDT VARCHAR(10)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS MonHoc (
    MaMH VARCHAR(50) PRIMARY KEY,
    TenMH VARCHAR(50),
    MaGV VARCHAR(20),
    CONSTRAINT FK_MonHoc_GiaoVien FOREIGN KEY (MaGV)
        REFERENCES GiaoVien(MaGV)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BangDiem (
    MaHS VARCHAR(20),
    MaMH VARCHAR(50),
    DiemThi INT,
    NgayKT DATETIME,
    PRIMARY KEY (MaHS, MaMH),
    CONSTRAINT FK_BangDiem_HocSinh FOREIGN KEY (MaHS)
        REFERENCES HocSinh(MaHS),
    CONSTRAINT FK_BangDiem_MonHoc FOREIGN KEY (MaMH)
        REFERENCES MonHoc(MaMH)
) ENGINE=InnoDB;

-- KIEM TRA KET QUA
SHOW TABLES;
SHOW CREATE TABLE HocSinh;
SHOW CREATE TABLE GiaoVien;
SHOW CREATE TABLE MonHoc;
SHOW CREATE TABLE BangDiem;
